{{- range $val := list "a" "b" }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo-{{$val}}
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 10
      - pause: {duration: 2m}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo-{{$val}}
  template:
    metadata:
      labels:
        app: rollouts-demo-{{$val}}
    spec:
      containers:
      - name: rollouts-demo-{{$val}}
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
{{ end -}}
